version: 1.0.{build}
skip_tags: true
image: Visual Studio 2022
install:
  - cinst dotnet-sdk --version 6.0.201  
environment:
  NuGetOrgApiKey: 
    secure: u8JpW5kkti8pMi+ra2QcXTJPhkHCA8pkKSiiZOJbcS/vFVHNvF3W8qw1Fy2If6a7
  PUBLIC_NUGET_FEED_NAME: nuget.org
  PUBLIC_NUGET_FEED_SOURCE: https://www.nuget.org/
build_script:
- cmd: ./build.cmd
test: off
artifacts:
- path: ./artifacts/*